name: "Test build of Ubuntu image when Dockerfile is changed"
on:
  push:
    paths:
    - 'Dockerfile.Ubuntu'
    branches-ignore:
    - main
  pull_request:
    paths:
    - 'Dockerfile.Ubuntu'
  workflow_dispatch:
jobs:
  rebuild-container:
    name: "Build image with cache"
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: "Checkout repository"
        uses: "actions/checkout@v2.3.4"
      -
        name: Build image
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          push: false
          tags: |
            ${{ github.repository_owner }}/simple-monerod:ubuntu-test
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/simple-monerod:ubuntu
          cache-to: type=inline
      - name: Test image (basic)
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ github.repository_owner }}/simple-monerod:ubuntu-test
          run: monerod --version
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
