name: "Test build of image when Dockerfile is changed"
on:
  push:
    paths:
    - 'Dockerfile'
    branches-ignore:
    - main
  pull_request:
    paths:
    - 'Dockerfile'
  workflow_dispatch:
jobs:
  rebuild-container:
    name: "Build image with cache"
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: "Checkout repository"
        uses: "actions/checkout@v3"
      -
        name: Build image
        id: docker_build
        uses: docker/build-push-action@v2.9.0
        with:
          push: false
          tags: simple-monerod:alpine-test
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/simple-monerod:alpine
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
