name: Build and scan container for vulnerabilities with Trivy

on:
  push:
    paths:
    - 'Dockerfile'
  pull_request:
    paths:
    - 'Dockerfile'
  schedule:
    - cron: '22 14 * * 0'
  workflow_dispatch:

jobs:
  build:
    name: Build and scan images
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      - 
        name: Build Alpine image from Dockerfile
        uses: docker/build-push-action@v4.1.1
        with:
          push: false
          load: true
          tags: sethforprivacy/simple-monerod:alpine
      - 
        name: Run Trivy vulnerability scanner against Alpine image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'sethforprivacy/simple-monerod:alpine'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - 
        name: Upload Alpine Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
