name: Build and scan container for vulnerabilities with Trivy

on:
  push:
    paths:
    - 'Dockerfile'
  pull_request:
    paths:
    - 'Dockerfile'
  schedule:
    - cron: '22 14 * * 0'

jobs:
  build:
    name: Build and scan images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Build Alpine image from Dockerfile
        run: |
          docker build -f Dockerfile -t sethforprivacy/simple-monerod:alpine .

      - name: Run Trivy vulnerability scanner against Alpine image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'sethforprivacy/simple-monerod:alpine'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Alpine Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
