name: "Update Image"
on:
  schedule:
    - cron: "0 12 * * *" # Run every day at noon.
jobs:
  rebuild-container:
    name: "Rebuild Container"
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo.
      - name: "Checkout"
        uses: "actions/checkout@v2"

      # Build and push the repo.
      - name: "Build and Push"
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/simple-monerod
          tags: latest
          tag_with_ref: true
          add_git_labels: true
          tag_with_sha: true